Added Set and Get to "currentDirtCapacity"
Added set and get because when writing tests, I kept ecountering an
error: "RobotController.currentDirtCapacity is not visible". So I either
can make "currentDirtCapacity" a public int or add get and set to the
variable which I though was more useful.